### ISSUE TITLE
Europe

### ISSUE THREAD

**Issue by finnp** [paeria/Hexi-sayhello#1]
Hey,

i love your service. @yosuke_furukawa already showed me the english help page. How much are the shipping costs from Japan to Germany (Berlin) for let's say 100 stickers?

Best,
Finn

**Comment by yosuke-furukawa** [comment]
Thank you for your speedy response :D 
Actually Japan is 2 a.m. my co-worker is sleeping... so sorry...
please wait a moment.

**Comment by yosuke-furukawa** [comment]
@finnp 
shipping cost is 4.5€.
If you would like to print 100 stickers, the sticker price is 86.5€.
So you can buy 100 stickers by 91€ at the total.
We can send you the stickers for 2 weeks.

**Comment by finnp** [comment]
@yosuke-furukawa 
Thanks for that info, sounds good. I would actually like to get 2 different kind of stickers, but the designs are not finished yet. I am going to come back at you, when they are ready.

**Comment by finnp** [comment]
I just purchased the stickers with your new English interface :)

Just to check. I didn't see the dimensions anywhere. Will it be conform to https://github.com/terinjokes/StickerConstructorSpec ?

**Comment by finnp** [comment]
PS: Can you confirm that I ordered 100 stickers? I feel like it didn't work.

**Comment by yosuke-furukawa** [comment]
@finnp thank you for purchasing. We will confirm your order.

> Will it be conform to https://github.com/terinjokes/StickerConstructorSpec ?

YES! We have printed 2 kinds of stickers. see here!!

https://github.com/nodeschool/tokyo/issues/10#issuecomment-92994977

**Comment by yosuke-furukawa** [comment]
@finnp 

> PS: Can you confirm that I ordered 100 stickers? I feel like it didn't work.

We confirmed your order!  Thank you!!
And we have ordered your stickers to a printer service company.
We can send you the stickers in 2 weeks. 
please wait and if you have some trouble, feel free to ask me :D

**Comment by finnp** [comment]
Thanks, awesome. Looking forward to have the stickers.

**Comment by finnp** [comment]
@yosuke-furukawa Do you know when the stickers will arrive? Have you already send them?

**Comment by yosuke-furukawa** [comment]
@finnp We have already ordered your stickers to our printing service. We can get your stickers until this Friday. And We will ship them as soon as possible. You can see the stickers in 11th May without any problem.

**Comment by yosuke-furukawa** [comment]
@finnp We will report your sticker progress in detail. 
- [x] order stickers to our printing service.
- [ ] print stickers
- [ ] arrive stickers in Hexi office.
- [ ] send stickers to you
- [ ] confirm stickers by you

**Comment by finnp** [comment]
@yosuke-furukawa Thank you, that's awesome :sparkles:

**Comment by yosuke-furukawa** [comment]
@finnp We confirmed your sticker. We will send you in tomorrow. Please wait !!

**Comment by yosuke-furukawa** [comment]
@finnp We sent stickers to you ! please confirm stickers when reaced.

**Comment by yosuke-furukawa** [comment]
@finnp We are confirming your sticker status, Our postal service has already shipped from Japan on their Web app. We will confirm it on tomorrow. Sorry for delay.

**Comment by finnp** [comment]
@yosuke-furukawa Haven't received them yet. Do you have an expected date?

**Comment by yosuke-furukawa** [comment]
@finnp 
We are sorry for delay.

I confirmed the status, the status is `In Customs` on Germany.
We have shipped your sticker on 4th May. The detail is here.

https://trackings.post.japanpost.jp/services/srv/search/direct?searchKind=S004&locale=en&reqCodeNo1=RR912514325JP&x=10&y=13

(This is a Japanese website, If you can check the international epacket on Germany, the status may be changed. epacket id is RR912514325JP. )

We would like to reach you until NodeSchool International Day. But we don't understand how long customs check. We are sorry that we did not predict the customs check period....

__We will refund you when the stickers are not received until NodeSchool International Day.__

**Comment by finnp** [comment]
Hey @yosuke-furukawa,

thanks for all the updates. Sadly the stickers were not here in time. Also according to the website of the Post Japan, the package is delivered, but I didn't receive anything. I will try to contact the local post office, maybe they can help and find the packacke.

**Comment by yosuke-furukawa** [comment]
@finnp 
Thank you for sharing status. I am happy to communicate with you on International Day :D 

> Sadly the stickers were not here in time

As promised, we will refund you. sorry for late. We should choose [Express Mail Service](https://www.post.japanpost.jp/int/ems/index_en.html). 

>  I didn't receive anything

Please confirm your local post office.  If the post office cannot solve the problem, I will confirm our post office.

We apologize that we have not consider the customs check period.

**Comment by finnp** [comment]
Hey @yosuke-furukawa, yes that was a really great start for our event.

The stickers now arrived and they look pretty good. :smile: 

I would really appreciate the refund for the stickers though. I might be ordering some NodeSchool stickers at hexi.pics again soon, but I have to consider the Custom costs and delivery next time.

**Comment by yosuke-furukawa** [comment]
@finnp What a relief! I am so glad to hear the news.
We are investigating how to deliver to Germany more quickly.
on the next time, we will use [Express Mail Service](https://www.post.japanpost.jp/int/ems/index_en.html).

Thank you. 
We should improve our service more and more.
